name: 'data_engineering_showcase'
version: '1.0.0'
config-version: 2

profile: 'data_engineering_showcase'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  data_engineering_showcase:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    mart:
      +materialized: table
      +schema: mart

seeds:
  data_engineering_showcase:
    +schema: raw
    +quote_columns: false 