version: 2

models:
  - name: fct_customer_orders
    description: Fact table containing customer order information
    columns:
      - name: order_key
        description: Surrogate key for the fact table
        tests:
          - unique
          - not_null
      - name: order_id
        description: Order ID from source system
        tests:
          - not_null
      - name: customer_id
        description: Customer ID from source system
        tests:
          - not_null
      - name: customer_name
        description: Customer's full name
      - name: customer_email
        description: Customer's email address
      - name: customer_country
        description: Customer's country
      - name: order_date
        description: Date the order was placed
        tests:
          - not_null
      - name: product_id
        description: Product ID from source system
      - name: product_name
        description: Name of the product
      - name: product_category
        description: Category of the product
      - name: quantity
        description: Quantity of product ordered
      - name: unit_price
        description: Unit price of product
      - name: total_amount
        description: Total amount of the order
      - name: order_status
        description: Status of the order
      - name: order_year
        description: Year of the order
      - name: order_month
        description: Month of the order
      - name: order_day
        description: Day of the order
      - name: order_day_of_week
        description: Day of week of the order
      - name: updated_at
        description: When the record was last updated

  - name: dim_customers
    description: Customer dimension table
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name
      - name: last_name
        description: Customer's last name
      - name: full_name
        description: Customer's full name
      - name: email
        description: Customer's email address
      - name: gender
        description: Customer's gender
      - name: country
        description: Customer's country
      - name: created_at
        description: When the customer was created
      - name: total_orders
        description: Total number of orders by the customer
      - name: lifetime_value
        description: Total amount spent by the customer
      - name: first_order_date
        description: Date of the customer's first order
      - name: last_order_date
        description: Date of the customer's most recent order
      - name: days_since_last_order
        description: Number of days since the customer's last order
      - name: customer_segment
        description: Segment the customer belongs to based on RFM analysis
      - name: updated_at
        description: When the record was last updated

  - name: dim_products
    description: Product dimension table
    columns:
      - name: product_id
        description: Primary key for products
        tests:
          - unique
          - not_null
      - name: product_name
        description: Name of the product
      - name: category
        description: Category of the product
      - name: description
        description: Description of the product
      - name: price
        description: Price of the product
      - name: created_at
        description: When the product was created
      - name: order_count
        description: Number of orders for this product
      - name: total_quantity_sold
        description: Total quantity of this product sold
      - name: total_revenue
        description: Total revenue generated by this product
      - name: popularity
        description: Popularity category of the product (High, Medium, Low)
      - name: updated_at
        description: When the record was last updated

  - name: dim_weather_locations
    description: Weather location dimension table
    columns:
      - name: location_key
        description: Surrogate key for the location
        tests:
          - unique
          - not_null
      - name: location
        description: Location name
        tests:
          - not_null
      - name: country
        description: Country name
      - name: avg_temperature
        description: Average temperature for the location
      - name: min_temperature
        description: Minimum temperature for the location
      - name: max_temperature
        description: Maximum temperature for the location
      - name: avg_humidity
        description: Average humidity for the location
      - name: total_measurements
        description: Total number of weather measurements for the location
      - name: temperature_category
        description: Temperature category (Hot, Warm, Cool, Cold)
      - name: humidity_category
        description: Humidity category (High, Medium, Low)
      - name: updated_at
        description: When the record was last updated 