global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
  
  - job_name: 'airflow-webserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-webserver:8080']
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
  - job_name: 'warehouse'
    static_configs:
      - targets: ['warehouse-exporter:9187']

# Alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093' 